# Generated by Django 3.2.9 on 2021-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_from', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('current_title', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('canddiate_state', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_country', models.CharField(blank=True, max_length=255, null=True)),
                ('pref_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('total_exp', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('highestqualification', models.CharField(blank=True, db_column='highestQualification', max_length=255, null=True)),
                ('database_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'degrees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'industry_type',
                'managed': False,
            },
        ),
    ]
